name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-secrets:
    name: Detect secrets (detect-secrets)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets

      - name: Run detect-secrets scan
        id: detect
        run: |
          # Scan the repo for high-entropy strings and known secret patterns
          detect-secrets scan --all-files > .secrets.baseline || true
          detect-secrets audit .secrets.baseline || true

      - name: Fail if secrets found
        if: ${{ steps.detect.outcome == 'failure' || always() }}
        run: |
          # Parse the baseline for any secrets that are not marked as false positives
          if grep -q "" .secrets.baseline; then
            echo "Detect-secrets baseline generated. Review .secrets.baseline for potential secrets.";
          fi
          # We intentionally don't auto-fail here to avoid false positives blocking pushes; maintainers will review .secrets.baseline
          echo "Secret scan completed. If secrets are found, review .secrets.baseline and remediate.";
